version: 2.1

jobs:
  build-and-scan:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - checkout

      - run:
          name: Install Node and Java
          command: |
            apt-get update
            apt-get install -y curl unzip openjdk-17-jre
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs

      - run:
          name: Restore backend
          command: dotnet restore SecureAPI/SecureAPI.csproj

      - run:
          name: Build backend
          command: dotnet build SecureAPI/SecureAPI.csproj --configuration Release --no-restore

      - run:
          name: Build frontend
          command: |
            cd client
            npm install
            npm run build

      - run:
          name: Install SonarScanner
          command: |
            dotnet tool install --global dotnet-sonarscanner

      - run:
          name: Run SonarCloud Scan
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet sonarscanner begin \
              /k:"LeBeatrix_SecurePaymentApp" \
              /o:"lebeatrix" \
              /d:sonar.token="$SONAR_TOKEN" \
              /d:sonar.host.url="https://sonarcloud.io" \
              /d:sonar.branch.name=main \
              /d:sonar.exclusions="**/bin/**,**/obj/**,**/node_modules/**,**/build/**,**/.vs/**"
              dotnet build SecureAPI/SecureAPI.csproj --configuration Release
            dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

workflows:
  build:
    jobs:
      - build-and-scan