version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build-and-scan:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - checkout

      - run:
          name: Install Node
          command: |
            apt-get update
            apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs

      - run:
          name: Restore backend
          command: dotnet restore SecureAPI/SecureAPI.csproj

      - run:
          name: Build backend
          command: dotnet build SecureAPI/SecureAPI.csproj --configuration Release --no-restore

      - run:
          name: Build frontend
          command: |
            cd client
            npm install
            npm run build

      - sonarcloud/scan

workflows:
  build:
    jobs:
      - build-and-scan:
          context: sonarcloud